terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
  required_version = ">=1.8.4"  ### some test
}

locals {
  labels = length(keys(var.labels)) >0 ? var.labels: {
    "env"=var.env_name
    "project"="undefined"
  }
}

#создаем облачную сеть
resource "yandex_vpc_network" "network" {
  name = var.network_name == null ? "vpc-network" : var.network_name # Спорное выражение, но так мы проверяем на null
  description = "Generated by Dummy VPC module"
}

#создаем подсеть
# resource "yandex_vpc_subnet" "develop" {
#   #name           = var.subnet_names[0]
#   name = var.network_name == null ? "develop-${var.subnet_zones[0]}" : var.subnet_names[0]
#   zone           = var.subnet_zones[0]
#   network_id     = yandex_vpc_network.develop.id
#   v4_cidr_blocks = var.subnet_cidrs
# }

resource "yandex_vpc_subnet" "subnet" {
  #name           = var.subnet_names[0]
  #for_each = { for k,v in var.subnets: k => v }
  count = length(var.subnets)
  name = "${yandex_vpc_network.network.name}-${var.subnets[count.index].zone}-${format("%02s", count.index +1)}"
  zone = var.subnets[count.index].zone
  network_id = yandex_vpc_network.network.id
  v4_cidr_blocks = var.subnets[count.index].cidr
}
